JobFinder/ViewModels/Shared/JobTableRowViewModel.cs
using JobFinder.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobFinder.ViewModels
{
    public class JobTableRowViewModel
    {
        public Job Job { get; set; }


        [Display(Name = "Saved")]
        public bool SavedCheck { get; set; }

        [Display(Name = "Applied")]
        public bool AppliedCheck { get; set; }

        [Display(Name = "Interviewing")]
        public bool InterviewingCheck { get; set; }

        [Display(Name = "Offered")]
        public bool OfferedCheck { get; set; }
    }
}

JobFinder/Controllers/SettingsController.cs
using JobFinder.Models;
using JobFinder.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobFinder.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public SettingsController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public IActionResult ChangePassword() => View(new ChangePasswordViewModel());

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel changePasswordVM)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.GetUserAsync(User);
                var result = await userManager.ChangePasswordAsync(user, changePasswordVM.OldPassword, changePasswordVM.NewPassword);

                if (result.Succeeded)
                {
                    await signInManager.RefreshSignInAsync(user);
                    changePasswordVM.Success = true;
                }
                else foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(changePasswordVM);
        }
    }
}

JobFinder/Views/Shared/_JobTablePartial.cshtml
@model List<JobTableRowViewModel>


<table id="job-results">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Created</th>
            <th>Type</th>
            <th>Min Salary</th>
            <th>Max Salary</th>
            <th>Location</th>
            <th>Company</th>
            <th>URL</th>
            <th>
                <button id="save-all-changes">
                    <i class="fas fa-save"></i>
                    <span>Save all changes</span>
                </button>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tableRowVM in Model)
        {
            <partial name="_JobTableRowPartial" model="tableRowVM" />
        }
    </tbody>
</table>

JobFinder/Views/Shared/_JobTableRowPartial.cshtml
@model JobTableRowViewModel

@{
    System.Globalization.CultureInfo culture = null;
    if (!string.IsNullOrWhiteSpace(Model.Job.CultureName))
    {
        culture = System.Globalization.CultureInfo.CreateSpecificCulture(Model.Job.CultureName);
        culture.NumberFormat.CurrencyDecimalDigits = 0;
    }
}


<tr>
    <td>@Html.Raw(Model.Job.Title)</td>
    <td class="description">
        <details>
            <summary>Click to expand</summary>
            <hr />
            <p>@Html.Raw(Model.Job.Description)</p>
        </details>
    </td>
    <td class="createdAt">
        <time datetime="@Model.Job.CreatedAt">
            <span>@Model.Job.CreatedAt.ToShortDateString()</span>
            <br />
            @if (Model.Job.CreatedAt.TimeOfDay != TimeSpan.Zero)
            {
                <span>@Model.Job.CreatedAt.ToShortTimeString()</span>
            }
        </time>
    </td>
    <td class="jobType">
        @if (Model.Job.Schedule != null)
        {
            <span>@Model.Job.GetScheduleString()</span>
            <br />
        }
        <span>@Model.Job.EmploymentType</span>
    </td>
    <td class="salary">
        @if (Model.Job.MinSalary != null && culture != null)
        {
            <span>@string.Format(culture, "{0:C}", Model.Job.MinSalary)</span>
        }
    </td>
    <td class="salary">
        @if (Model.Job.MaxSalary != null && culture != null)
        {
            <span>@string.Format(culture, "{0:C}", Model.Job.MaxSalary)</span>
        }
    </td>
    <td>@Model.Job.Location</td>
    <td>@Model.Job.Company</td>
    <td>
        <a href="@Model.Job.URL">Link</a>
    </td>
    <td class="save">
        <details>
            <summary>Add to</summary>
            <hr />
            <form asp-controller="MyJobs" asp-action="ChangeSaveCategory" method="post">
                <div class="hidden">
                    <input asp-for="Job.ID" type="hidden" />
                    <input asp-for="Job.Title" type="hidden" />
                    <input asp-for="Job.Description" type="hidden" />
                    <input asp-for="Job.CreatedAt" type="hidden" />
                    <input asp-for="Job.Company" type="hidden" />
                    <input asp-for="Job.Location" type="hidden" />
                    <input asp-for="Job.URL" type="hidden" />
                    <input asp-for="Job.MinSalary" type="hidden" />
                    <input asp-for="Job.MaxSalary" type="hidden" />
                    <input asp-for="Job.CultureName" type="hidden" />
                    <input asp-for="Job.Schedule" type="hidden" />
                    <input asp-for="Job.EmploymentType" type="hidden" />
                    <input asp-for="Job.UsersSavedBy" type="hidden" />
                    <input asp-for="Job.UsersAppliedBy" type="hidden" />
                    <input asp-for="Job.UsersInterviewing" type="hidden" />
                    <input asp-for="Job.UsersOfferedTo" type="hidden" />
                </div>

                <div>
                    <input asp-for="SavedCheck" />
                    <label asp-for="SavedCheck"></label>
                </div>
                <div>
                    <input asp-for="AppliedCheck" />
                    <label asp-for="AppliedCheck"></label>
                </div>
                <div>
                    <input asp-for="InterviewingCheck" />
                    <label asp-for="InterviewingCheck"></label>
                </div>
                <div>
                    <input asp-for="OfferedCheck" />
                    <label asp-for="OfferedCheck"></label>
                </div>
                <div class="jobSaveSubmit">
                    <button type="submit">
                        <i class="fas fa-save"></i>
                        <span>Save changes</span>
                    </button>

                    <div class="saveProgress"></div>
                </div>
            </form>
        </details>
    </td>
</tr>

JobFinder/Views/Shared/_JobTableScriptsPartial.cshtml
<!-- Change save category AJAX -->
<script>
    $('#job-results td.save form').submit(function (event) {
        event.preventDefault();

        const form = $(this);
        const url = form.attr('action');
        const saveProgress = form.find('.saveProgress');

        saveProgress.removeClass('red');
        saveProgress.html('Saving...');

        $.post(url, form.serialize(), function () {
            saveProgress.html('Saved!');
        })
            .fail(function () {
                saveProgress.addClass('red');
                saveProgress.html('Could not save');

                alert('There was an error changing the save category.');
            });
    });
</script>

<!-- "Save all changes" button -->
<script>
    $('#job-results button#save-all-changes').click(function () {
        const forms = $('#job-results td.save form');
        forms.submit();
    });
</script>

JobFinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - JobFinder</title>
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    </head>

    <body>
        <header>
            <nav id="header-nav">
                <div>
                    <form asp-controller="Home" asp-action="Index" method="get">
                        <button type="submit">
                            <i class="fas fa-search"></i>
                            <span>Search</span>
                        </button>
                    </form>

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <form asp-controller="MyJobs" asp-action="Saved" method="get">
                            <button type="submit">
                                <i class="fas fa-archive"></i>
                                <span>My jobs</span>
                            </button>
                        </form>
                    }
                </div>

                <span id="site-title" onclick="javascript: location.href = '@Url.Action("Index", "Home")'">
                    JobFinder
                </span>

                <div>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <form asp-controller="Settings" asp-action="ChangePassword" method="get">
                            <button type="submit">
                                <i class="fas fa-cog"></i>
                                <span>Settings</span>
                            </button>
                        </form>
                        <form asp-controller="Account" asp-action="Logout" method="post">
                            <button type="submit">
                                <i class="fas fa-sign-out-alt"></i>
                                <span>Log out</span>
                            </button>
                        </form>
                    }
                    else
                    {
                        <form asp-controller="Account" asp-action="Login" method="get">
                            <button type="submit">
                                <i class="fas fa-sign-in-alt"></i>
                                <span>Log in</span>
                            </button>
                        </form>
                        <form asp-controller="Account" asp-action="Register" method="get">
                            <button type="submit">
                                <i class="fas fa-user-plus"></i>
                                <span>Register</span>
                            </button>
                        </form>
                    }
                </div>
            </nav>
        </header>

        <main>
            @RenderBody()
        </main>

        <footer>
            <small>&copy; 2021 - Charles Morgan</small>
        </footer>

        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>